---
AWSTemplateFormatVersion: '2010-09-09'

Resources:
  Lambda:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        S3Bucket: @{S3Bucket}
        S3Key: @{S3Key}
      FunctionName: @{FunctionName}
      Handler: 'index.handler'
      Role: !GetAtt LambdaExecRole.Arn
      Runtime: @{Runtime}
      Timeout: @{Timeout}
  
  LambdaExecRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub '@{FunctionName}_${AWS::Region}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement: @{RoleStatement}
      Policies:
        - PolicyName: !Sub '@{FunctionName}_${AWS::Region}'
          PolicyDocument:
            Version: '2012-10-17'
            Statement: @{PolicyStatement}

  LambdaLogsGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      LogGroupName: '/aws/lambda/@{FunctionName}'
      RetentionInDays: 30
      
Outputs:
  LambdaArn:
    Value: !GetAtt Lambda.Arn
    Export:
      Name: '@{FunctionName}'